"""baseline schema

Revision ID: 8ff743c44fc7
Revises: 
Create Date: 2026-07-05 22:10:30.688752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff743c44fc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('lat_round', sa.Float(), nullable=False),
    sa.Column('lon_round', sa.Float(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('wikipedia_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('lat_round', 'lon_round')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('camera', sa.String(length=256), nullable=True),
    sa.Column('thumb_path', sa.String(length=4096), nullable=True),
    sa.Column('preview_path', sa.String(length=4096), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_path'), ['path'], unique=True)

    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_day'), ['day'], unique=True)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('thumb_path', sa.String(length=4096), nullable=True),
    sa.Column('preview_path', sa.String(length=4096), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_path'), ['path'], unique=True)

    op.create_table('aesthetic_scores',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('nima_score', sa.Float(), nullable=True),
    sa.Column('ap25_score', sa.Float(), nullable=True),
    sa.Column('personal_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('classical_scores',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('blur', sa.Float(), nullable=True),
    sa.Column('exposure', sa.Float(), nullable=True),
    sa.Column('faces_count', sa.Integer(), nullable=True),
    sa.Column('eyes_open_ratio', sa.Float(), nullable=True),
    sa.Column('auto_reject', sa.Boolean(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('embeddings',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('siglip', sa.LargeBinary(), nullable=False),
    sa.Column('aesthetic_iqa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('face_index', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('bbox_x', sa.Integer(), nullable=False),
    sa.Column('bbox_y', sa.Integer(), nullable=False),
    sa.Column('bbox_w', sa.Integer(), nullable=False),
    sa.Column('bbox_h', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_embeddings_photo_id'), ['photo_id'], unique=False)

    op.create_table('moments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_photo_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['primary_photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moments_primary_photo_id'), ['primary_photo_id'], unique=False)

    op.create_table('photo_categories',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('landscape_sim', sa.Float(), nullable=True),
    sa.Column('portrait_sim', sa.Float(), nullable=True),
    sa.Column('object_sim', sa.Float(), nullable=True),
    sa.Column('primary_category', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('photo_ratings',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    # NOTE: photo_tags is intentionally created here in its PRE-source shape:
    # PK (photo_id, tag), no ``source`` column. The follow-up revision
    # ('add source to photo_tags PK') ports the historical hand-rolled migration
    # (_migrate_add_source_column) that adds the column and rebuilds the PK. This
    # lets pre-source databases in the wild stamp this baseline honestly and then
    # upgrade to head, while the follow-up revision is a guarded no-op for DBs
    # that already have the source column.
    op.create_table('photo_tags',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id', 'tag')
    )
    with op.batch_alter_table('photo_tags', schema=None) as batch_op:
        batch_op.create_index('ix_photo_tags_tag', ['tag'], unique=False)

    op.create_table('pipeline_states',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('classical_done', sa.Boolean(), nullable=False),
    sa.Column('embedding_done', sa.Boolean(), nullable=False),
    sa.Column('vl_done', sa.Boolean(), nullable=False),
    sa.Column('ordering_done', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    with op.batch_alter_table('pipeline_states', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_states_work', ['classical_done', 'embedding_done'], unique=False)

    op.create_table('story_items',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('scene_label', sa.String(length=64), nullable=True),
    sa.Column('scene_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'rank')
    )
    op.create_table('swipes',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('swiped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Integer(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=False),
    sa.Column('departed_at', sa.DateTime(), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('cover_photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_story_id'), ['story_id'], unique=False)
        batch_op.create_index('ix_visits_story_rank', ['story_id', 'rank'], unique=False)

    op.create_table('moment_members',
    sa.Column('moment_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('moment_id', 'photo_id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('cover_face_embedding_id', sa.Integer(), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('centroid', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cover_face_embedding_id'], ['face_embeddings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_persons',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('face_embedding_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['face_embedding_id'], ['face_embeddings.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'person_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_persons')
    op.drop_table('persons')
    op.drop_table('moment_members')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index('ix_visits_story_rank')
        batch_op.drop_index(batch_op.f('ix_visits_story_id'))

    op.drop_table('visits')
    op.drop_table('swipes')
    op.drop_table('story_items')
    with op.batch_alter_table('pipeline_states', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_states_work')

    op.drop_table('pipeline_states')
    with op.batch_alter_table('photo_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_photo_tags_tag')

    op.drop_table('photo_tags')
    op.drop_table('photo_ratings')
    op.drop_table('photo_categories')
    with op.batch_alter_table('moments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moments_primary_photo_id'))

    op.drop_table('moments')
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_embeddings_photo_id'))

    op.drop_table('face_embeddings')
    op.drop_table('embeddings')
    op.drop_table('classical_scores')
    op.drop_table('aesthetic_scores')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_path'))

    op.drop_table('videos')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_day'))

    op.drop_table('stories')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_path'))

    op.drop_table('photos')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
